use_sim_time: true
graph: complex_final
init_bots: 6
init_locations: ''
done: false
sim_length: 30000
random_string: without_intent_reactive_flag120
algo_name: without_intent_reactive_flag
no_of_deads: 8
run_id: 2