use_sim_time: true
graph: grid_5_5_final
init_bots: 1
init_locations: ''
done: false
sim_length: 30000
random_string: without_intent_reactive_flag187
algo_name: without_intent_reactive_flag
no_of_deads: 12
run_id: 0