use_sim_time: true
graph: complex_final
init_bots: 2
init_locations: ''
done: false
sim_length: 30000
random_string: without_intent_reactive_flag77
algo_name: without_intent_reactive_flag
no_of_deads: 0
run_id: 1