use_sim_time: true
graph: grid_5_5
init_bots: 6
init_locations: ''
done: false
sim_length: 30000
random_string: without_intent_reactive_flag53
algo_name: without_intent_reactive_flag
no_of_deads: 3
run_id: 1