use_sim_time: true
graph: grid_5_5
init_bots: 2
init_locations: ''
done: false
sim_length: 30000
random_string: without_intent_reactive_flag28
algo_name: without_intent_reactive_flag
no_of_deads: 8
run_id: 0