use_sim_time: true
graph: complex_final
init_bots: 5
init_locations: ''
done: false
sim_length: 30000
random_string: without_intent_reactive_flag34
algo_name: without_intent_reactive_flag
no_of_deads: 7
run_id: 0