use_sim_time: true
graph: complex_final
init_bots: 2
init_locations: ''
done: false
sim_length: 30000
random_string: without_intent_reactive_flag82
algo_name: without_intent_reactive_flag
no_of_deads: 3
run_id: 0